### ISSUE TITLE
Error running Reconstruction

### ISSUE THREAD

**Issue by idolawoye** [Integrative-Transcriptomics/Daccor#2]
I am trying to run reconstruction on my Ubuntu server 18.04. The version of java installed on the server is 11. Using the shell script in the examples directory. I have successfully identified the repeats in the reference genome, but when I try to reconstruct the sequence sample I encounter this error:

`Starting Reconstruction`
`reference eager config file not found`
`found 0 already reconstructed genomes`
`found 0 repeats to reconstruct`
`found 1 samples to reconstruct`
`starting reconstruction for 1 samples`
         `for sample SRR3584843`
`reconstructing for sample: SRR3584843`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/idow/software/Daccor/Releases/Daccor-1.0.0.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.io.IOException: Cannot run program "eagercli": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at automaticReconstruction.ReconstructSequences.createEagerConfigsAndRunReconstruction(ReconstructSequences.java:201)
        at automaticReconstruction.ReconstructSequences.<init>(ReconstructSequences.java:88)
        at userinterface.CommandLineInterface.runReconstruction(CommandLineInterface.java:157)
        at userinterface.CommandLineInterface.<init>(CommandLineInterface.java:90)
        at userinterface.Main.main(Main.java:13)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 6 more`

**Kindly help with this as I don't know what's wrong**

**Comment by alex-seitz** [comment]
Hello,
sorry for the late answer,
Unfortunately Daccor currently runs up to Java Version 8 and was only tested up to Java Version 7 (as written in the README)
I hope this information helps you and can resolve the issue, if not, please let me know.
Best,
Alexander Seitz

**Comment by idolawoye** [comment]
Thank you for your response. I am running Daccor on a different PC which has java version 8 installed and I am having a little issue running the Identify pipeline. I ran Daccor Identify using the default options and it produced empty `.fasta`, `.bed` files and a `.csv` file with 0 repeats.
I am puzzled why this happened. Any ideas?
Here's the output on the screen:

$ java -jar Daccor-1.0.0.jar identify -i sequence.fasta -o salmonella
running combined
running kmer identification
running program
merging regions
merging low complex regions
filtering
Repetitive regions for sequence null are identified.
Output was generated

**Comment by alex-seitz** [comment]
Hello,
sorry for my late answer, I was travalling the last days. Can you please tell me which sequence you used, so that I can try it myself and look for the problem? Thank you
Best,
Alex

**Comment by idolawoye** [comment]
Hello, Thanks for your response. I ran DACCOR identify on the TB ref genome (H37Rv) using the below commands:
`java -jar Bio*/Daccor/Releases/Daccor-1.0.0.jar identify -i tbref.fna -k 31 -m 0 -o TBref -p 4 -t 50`

The output was:
running combined
running kmer identification
running program
merging regions
merging low complex regions
filtering
Repetitive regions for sequence null are identified.
Output was generated
I have also attached the `.csv` file that was generated.
[TBref_k31_Mis0_Thres50_Summary.csv.zip](https://github.com/Integrative-Transcriptomics/Daccor/files/2718285/TBref_k31_Mis0_Thres50_Summary.csv.zip)

[tbref.fna.zip](https://github.com/Integrative-Transcriptomics/Daccor/files/2718286/tbref.fna.zip)

**Comment by alex-seitz** [comment]
Hey,
the error appears to come from an out of memory exception. Unfortunately this error happens within the multithreadding and is thus caught internally by the Java Library, which is why we do not get an output.
if you run it with
java -Xmx8G -jar ...
it should work
I will try to add an error message, but currently have no idea of how this might work

**Comment by idolawoye** [comment]
Thanks a lot Alex
