### ISSUE TITLE
Daccor Combine

### ISSUE THREAD

**Issue by idolawoye** [Integrative-Transcriptomics/Daccor#3]
Hello, 
I got stuck at the combine bit. I am not sure of what inputs to use for the reconstructed genome (-g) and the repeats (-r) here. I have ran so many trials but I keep getting 0 repeats to reconstruct message.
I ran the reconstruct bit using the EAGER pipeline which generated about 10 folders (FastQC, AdaClip, Mapper, etc) some with BAM files but none with a FASTA file.
Do I use the identify repeats output for -r? I have tried that but I am still getting same '0 repeats to reconstruct' message.
I will be happy if you can assist.
Thanks a lot

**Comment by alex-seitz** [comment]
Hello,
An example for the -r input-file can be found in the examples folder with the name configCombineRepeats.txt. Basically it is a tab-separated file that contains in the first column the sample name and in the second one the path to the reconstructed fasta-File, generated by the "reconstruct" subprogram.

However, if you want to run it from the repeat-Identification until the combination and the EAGER-Pipeline is installed on the server, I would suggest you try to run the complete pipeline like this:
java -jar Releases/Daccor-1.0.0.jar pipeline -f <configFQ> -i <refFASTA> -o <OUTPUT>
where the configFQ looks like the file configReconstructFQ.txt in the example directory. A tab separated file with the sample-name in the first column and the path to the forward and reverse reads in the second and third columns.

I hope this helps you

Best

Alex

**Comment by idolawoye** [comment]
Hi, 

Thank you for email, I was able to run the EAGER-pipeline and I have a series of outputs. The `.fasta`, `.csv`, `.bed` and a folder containing the identified repeats, which also has a subfolder with sample name containing the `.xml` config file. How do I get the combined sample with the reconstructed regions?
Here is the screen message using the test sample:

java -jar Daccor-1.0.0.jar pipeline -f pipeFQ.txt -i ~/Downloads/BIO/Daccor/examples/data/identify/GCF* -o OUTPUT
running combined
running kmer identification
Repetitive kmers for sequence >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome are identified.
finished running kmer identification
running program
merging regions
merging low complex regions
filtering
Repetitive regions for sequence null are identified.
Output was generated
finished analyzing reference
starting to reconstruct >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome
reference eager config file not found
found 0 already reconstructed genomes
found 1 samples to reconstruct
starting reconstruction for 1 samples
         for sample data
reconstructing for sample: data
combining reconstruction for data

**Comment by alex-seitz** [comment]
Hi,
I'm sorry, but I can't really follow you.
Can you run the following command from inside the example directory and see if it works?:
java -jar ../Releases/Daccor-1.0.0.jar pipeline -i data/identify/GCF_000008605.1_ASM860v1_genomic.fna -f configReconstructFQ.txt -o testout
It should create an example run of one syphilis sample.
For this eager must be installed and callable using the eagercli command.

Best,
Alex

**Comment by idolawoye** [comment]
Hello Alex,
I have eagercli callable on the command line and I ran the pipeline on the data provided in the example directory. I only edited the `configReconstructFQ.txt` file to contain the path to the FastQ files in the data/ directory (SRR3584843_R1.fastq.gz and SRR3584843_R2.fastq.gz) but after running it I still get:

```
running combined
running kmer identification
Repetitive kmers for sequence >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome are identified.
finished running kmer identification
running program
merging regions
merging low complex regions
filtering
Repetitive regions for sequence null are identified.
Output was generated
finished analyzing reference
starting to reconstruct >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome
reference eager config file not found
found 0 already reconstructed genomes
found 1 samples to reconstruct
starting reconstruction for 1 samples
for sample data
reconstructing for sample: data
combining reconstruction for data
```
After the run I cannot find the output genome that has been combined with the identified repeats.
Thanks

**Comment by alex-seitz** [comment]
Hey,
how did you change the configReconstructFQ?
I did not need to change it at all so that it runs on my side. The fact that it says "for sample data" seems that it somehow does not get the correct sample name from the file.
If I run it from inside the example-directory, with the command I posted yesterday it runs without errors
Best,
Alex

**Comment by idolawoye** [comment]
I created a new configReconstructFQ file having the path to the FASTQ files in my directory. However, running the original one straight from the examples directory produced this outcome.


![img_20190111_165403](https://user-images.githubusercontent.com/39491421/51044701-09935500-15c2-11e9-862d-6ee10e3ce595.jpg)

**Comment by alex-seitz** [comment]
Ok, sorry had the wrong file in the back of my head.
Yes, you should change the paths, however, the line "for sample B3" shows that it now parsed the file correctly. In your case it always said "for sample data".
It also appears that you are running it with java9? I just testet it with the following command with java version "1.8.0_162" (should work without changing anything):

java -jar ../Releases/Daccor-1.0.0.jar pipeline -i data/identify/GCF_000008605.1_ASM860v1_genomic.fna -f data/exampleFQConfig.txt -o testout

From within the example directory.

I hope this helps you.

There you should see the line "for sample SRR3584843".

It should create a directory starting with the current date in the example directory, After everything finished, the resulting There should be three files starting with "SRR3584843" (the specified sample name in the exampleFQConfig.txt). A fasta-file with the combined reconstruction, and two files containing the repetitive base-positions that could and could not be reconstructed.

Best,

Alex

**Comment by idolawoye** [comment]
Hello Alex,
I followed the steps you highlighted in your last comment and whilst running the pipeline I have this on my screen:
```
running combined
running kmer identification
Repetitive kmers for sequence >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome are identified.
finished running kmer identification
running program
merging regions
merging low complex regions
filtering
Repetitive regions for sequence null are identified.
Output was generated
finished analyzing reference
starting to reconstruct >NC_000919.1 Treponema pallidum subsp. pallidum str. Nichols complete genome
reference eager config file not found
found 0 already reconstructed genomes
found 1 samples to reconstruct
starting reconstruction for 1 samples
	 for sample SRR3584843
reconstructing for sample: SRR3584843
combining reconstruction for SRR3584843
```
In the directory with today's date that was created however does not have three files like you stated. Instead I have 58 fasta files that contain the identified repetitive regions and a folder named SRR3584843. In that folder I have a config file and another folder named 'tmp_reconstruction' containing tmp folders. Below is a screenshot of resulting folder.

https://www.dropbox.com/s/hvrlg31ltzxcm85/Screenshot%202019-01-14%2011.11.23.png?dl=0
PS: I'm running on Java 1.8.0_141

**Comment by alex-seitz** [comment]
The three files should appear directly in the example directory, not the subdirectory with the date.
Somehow EAGER could not be run, the directories 1-AdapClip etc should be contained in the directory that you posted a screenshot of. It ran through on my side.
In addition to the fasta-files in the subdirectory with the current date, the bwa-index files should also be present there (.fai, .sa, .pac. .btw, .ann, .amb) If they are not present, Daccor was not able to start the EAGER pipeline

**Comment by idolawoye** [comment]
Do you know what the issue may be then?

**Comment by alex-seitz** [comment]
I'm sorry, currently not. Can you try and run eagercli conf-EAGER.xml inside the SRR... folder you posted above? maybe there is an error there?

**Comment by idolawoye** [comment]
I tried to run eagercli on the config file but this is the output:

```
SRR3584843 acegid1$ eagercli conf-EAGER.xml
Please specify [n] input files to be used in the EAGER Pipeline. This could be for example: 

 - a folder with subfolders containing EAGER Configuration files, which will be then searched and executed.
 - a single EAGER Configuration file, created using the GUI.
 - (optional) a properties file, describing paths to tools required by the pipeline.

```
Something is wrong somewhere and I am not sure what it is exactly

**Comment by idolawoye** [comment]
However, I got a different output when running eagercli by executing it with java -jar

```
libs acegid1$ java -jar EAGER-CLI-1.92.55.jar ~/Downloads/BIO/Daccor/Releases/2019*/SRR*/conf-EAGER.xml
Found 1 input configuration files.
Processing file # 1
Schaffa, Schaffa, Genome baua!
Checking for file at path: /Users/acegid1/Downloads/BIO/Daccor/examples/data/identify/GCF_000008605.1_ASM860v1_genomic.dict

# ModulePoolPaths: [/Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R1.fastq.gz, /Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R2.fastq.gz]
# Module that will be now executed: CreateResultsDirectories
# Runtime of Module was: 0 seconds.
# Outputpath of ModulePool right now: [/Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R1.fastq.gz, /Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R2.fastq.gz]
# ModulePoolPaths: [/Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R1.fastq.gz, /Users/acegid1/Downloads/BIO/Daccor/Releases/data/SRR3584843_R2.fastq.gz]
# Module that will be now executed: ClipAndMergedefault
Exception in thread "main" java.io.IOException: Cannot run program "ClipAndMerge": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at Runner.ModuleRunner.run(ModuleRunner.java:67)
	at Runner.ModuleRunner.<init>(ModuleRunner.java:40)
	at Runner.ModulePool.start(ModulePool.java:78)
	at Runner.RunEAGER.executeAll(RunEAGER.java:104)
	at Runner.RunEAGER.<init>(RunEAGER.java:44)
	at Runner.RunEAGER.main(RunEAGER.java:68)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 6 more

```
my config file seems to be fine.
[conf-EAGER.xml.zip](https://github.com/Integrative-Transcriptomics/Daccor/files/2765206/conf-EAGER.xml.zip)

**Comment by alex-seitz** [comment]
It looks like you don't have the program ClipAndMerge installed.
The easiest way is probably to adapt the installation contained here:

https://github.com/apeltzer/ClipAndMerge/blob/master/arch-pkgbuild/PKGBUILD

( adapt the starter.sh to the correct path, rename it to ClipAndMerge, make it executable and put it to /usr/bin

Best,
Alex

**Comment by idolawoye** [comment]
Thanks for the tip. I encountered another error after solving that issue. I have qualimap installed which is callable as you can see here:
```
ACEGID1s-iMac:libs acegid1$ qualimap --help
Java memory size is set to 1200M
Launching application...

OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
QualiMap v.2.2.1
Built on 2016-10-03 18:14

usage: qualimap <tool> [options]

To launch GUI leave <tool> empty.

Available tools:

    bamqc            Evaluate NGS mapping to a reference genome
    rnaseq           Evaluate RNA-seq alignment data
    counts           Counts data analysis (further RNA-seq data evaluation)
    multi-bamqc      Compare QC reports from multiple NGS mappings
    clustering       Cluster epigenomic signals
    comp-counts      Compute feature counts

Special arguments: 

    --java-mem-size  Use this argument to set Java memory heap size. Example:
                     qualimap bamqc -bam very_large_alignment.bam --java-mem-size=4G

```
but it does not run in the eagercli pipeline:
```# Module that will be now executed: QualiMapDefault
Exception in thread "main" java.io.IOException: Cannot run program "qualimap": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at Runner.ModuleRunner.run(ModuleRunner.java:67)
	at Runner.ModuleRunner.<init>(ModuleRunner.java:40)
	at Runner.ModulePool.start(ModulePool.java:78)
	at Runner.RunEAGER.executeAll(RunEAGER.java:104)
	at Runner.RunEAGER.<init>(RunEAGER.java:44)
	at Runner.RunEAGER.main(RunEAGER.java:68)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```
What I did now is run qualimap using the command it could not execute in the log file which worked
```
ACEGID1s-iMac:libs acegid1$ qualimap bamqc -bam /Users/acegid1/Downloads/BIO/Daccor/Releases/20190114-111832rep_sep_output_testout_k17_Mis0_Thres51/SRR3584843/5-DeDup/SRR3584843_R1.fastq.merged.fq.bwamem.mapped.RG.sorted.cleaned.bam -nt 4 -outdir /Users/acegid1/Downloads/BIO/Daccor/Releases/20190114-111832rep_sep_output_testout_k17_Mis0_Thres51/SRR3584843/6-QualiMap/SRR3584843_R1.fastq.merged.fq.bwamem.mapped.RG.sorted.cleaned -outformat HTML --java-mem-size=64G 
Java memory size is set to 64G
Launching application...

OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
QualiMap v.2.2.1
Built on 2016-10-03 18:14

Selected tool: bamqc
Available memory (Mb): 33
Max memory (Mb): 68719
Thu Feb 07 12:31:27 WAT 2019		WARNING	Output folder already exists, the results will be saved there

Starting bam qc....
Loading sam header...
Loading locator...
Loading reference...
Number of windows: 400, effective number of windows: 400
Chunk of reads size: 1000
Number of threads: 4
Processed 50 out of 400 windows...
Processed 100 out of 400 windows...
Processed 150 out of 400 windows...
Processed 200 out of 400 windows...
Processed 250 out of 400 windows...
Processed 300 out of 400 windows...
Processed 350 out of 400 windows...
Processed 400 out of 400 windows...
Total processed windows:400
Number of reads: 150164
Number of valid reads: 131011
Number of correct strand reads:0

Inside of regions...
Num mapped reads: 131011
Num mapped first of pair: 0
Num mapped second of pair: 0
Num singletons: 0
Time taken to analyze reads: 3
Computing descriptors...
numberOfMappedBases: 24555856
referenceSize: 1138011
numberOfSequencedBases: 24552382
numberOfAs: 5679682
Computing per chromosome statistics...
Computing histograms...
Overall analysis time: 3
end of bam qc
Computing report...
Writing HTML report...
HTML report created successfully

Finished
```
The problem I have now is moving forward on the pipeline because if i run eagercli on the config file i still get this error even after running qualimap independently:
```
# Module that will be now executed: QualiMapDefault
Exception in thread "main" java.io.IOException: Cannot run program "qualimap": error=2, No such file or directory
```

**Comment by alex-seitz** [comment]
That is strange, maybe contact Alexander Peltzer at the EAGER repository with the problem of qualimap within EAGER.
If you don't want qualimap to run, you have to create the file "DONE.QualiMapDefault" within the 6-Qualimap directory. EAGER looks for this file to see if qualimap was already run.
But this is only a temporary sultion, I don't know why EAGER does not recognize qualimap on your server, sorry
